name = "ai-spend-monitor"
main = "src/index.ts"
compatibility_date = "2024-09-26"
# enable node compat for vitest/miniflare usage if needed
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"] # every 30 minutes

[[kv_namespaces]]
binding = "RAW_PAGES"
id = "4a66c2ce5f864ed6a5eb416346577868"
preview_id = "4a66c2ce5f864ed6a5eb416346577868"

[[d1_databases]]
binding = "DB"
database_name = "ai-spend-monitor-db"
database_id = "ef027717-5aaf-4b45-8659-3bf92f9c80da"
preview_database_id = "ef027717-5aaf-4b45-8659-3bf92f9c80da"
migrations_table = "d1_migrations"  # Optional: customize migration tracking table name
migrations_dir = "migrations"       # Optional: specify custom migration directory

[durable_objects]
bindings = [
  { name = "ROLLUP_DO", class_name = "RollupDO" }
]

[vars]
ENABLE_OPENAI = "true"
ENABLE_ANTHROPIC = "true"
ENABLE_VERTEX_BILLING_API = "true"
ENABLE_VERTEX_BQ = "false"
OPENAI_SOFT_CAP = "0"
OPENAI_HARD_CAP = "0"
ANTHROPIC_SOFT_CAP = "0"
ANTHROPIC_HARD_CAP = "0"
VERTEX_SOFT_CAP = "0"
VERTEX_HARD_CAP = "0"
GLOBAL_SOFT_CAP = "0"
GLOBAL_HARD_CAP = "0"
CRON_LOOKBACK_HOURS = "48"
ON_HARDCAP_WEBHOOK = ""
SLACK_WEBHOOK_URL = ""
ALERT_EMAIL_WEBHOOK = ""

# Durable Object migrations
[[migrations]]
tag = "v1" # A unique identifier for this migration
new_classes = ["RollupDO"]
